#!/bin/bash

cat << EOF > ui_index.c
// This file was generated by ui_index.gen.sh, do not edit it manually
#include "ui_index.h"

ui_obj_map ui_objects[] = {
$(grep "extern lv_obj_t \*" ui/ui.h | sed 's/extern lv_obj_t \*//g' | sed 's/;//g' | while read -r line; do
    echo "    {\"$line\", &$line},"
done)
};

const int ui_objects_size = sizeof(ui_objects) / sizeof(ui_objects[0]);

ui_img_map ui_images[] = {
$(grep "LV_IMG_DECLARE" ui/ui.h | sed 's/LV_IMG_DECLARE( //g' | sed 's/);//g' | while read -r line; do
    img_name=$(echo $line | awk -F'// ' '{print $2}' | sed 's/assets\///')
    img_var=$(echo $line | awk '{print $1}')
    echo "    {\"$img_name\", &$img_var},"
done)
};

const int ui_images_size = sizeof(ui_images) / sizeof(ui_images[0]);
EOF

echo "ui_index.c has been generated successfully."
