// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Boot_Screen
void ui_Boot_Screen_screen_init(void);
void ui_event_Boot_Screen( lv_event_t * e);
lv_obj_t *ui_Boot_Screen;
lv_obj_t *ui_Boot_Container_0;
lv_obj_t *ui_Boot_Container_1;
lv_obj_t *ui_Boot_Logo;


// SCREEN: ui_Settings_Overview_Screen
void ui_Settings_Overview_Screen_screen_init(void);
void ui_event_Settings_Overview_Screen( lv_event_t * e);
lv_obj_t *ui_Settings_Overview_Screen;
lv_obj_t *ui_Settings_Overview_Container_0;
lv_obj_t *ui_Settings_Overview_Container_1;
void ui_event_Settings_Overview_Header_Back_Button( lv_event_t * e);
lv_obj_t *ui_Settings_Overview_Header_Back_Button;
lv_obj_t *ui_Settings_Overview_Header_Back_Button_Icon;
lv_obj_t *ui_Settings_Overview_Header_Page_Name_Label;
lv_obj_t *ui_Settings_Overview_Container_2;
void ui_event_Settings_Overview_Network_Button( lv_event_t * e);
lv_obj_t *ui_Settings_Overview_Network_Button;
lv_obj_t *ui_Settings_Overview_Network_Button_Label;
void ui_event_Settings_Overview_Status_Button( lv_event_t * e);
lv_obj_t *ui_Settings_Overview_Status_Button;
lv_obj_t *ui_Settings_Overview_Status_Button_Label;
void ui_event_Settings_Overview_About_Button( lv_event_t * e);
lv_obj_t *ui_Settings_Overview_About_Button;
lv_obj_t *ui_Settings_Overview_About_Button_Label;
void ui_event_Settings_Overview_Reset_Device_Button( lv_event_t * e);
lv_obj_t *ui_Settings_Overview_Reset_Device_Button;
lv_obj_t *ui_Settings_Overview_Reset_Device_Button_Label;


// SCREEN: ui_Home_Screen
void ui_Home_Screen_screen_init(void);
void ui_event_Home_Screen( lv_event_t * e);
lv_obj_t *ui_Home_Screen;
lv_obj_t *ui_Home_Container_0;
lv_obj_t *ui_Home_Container_1;
lv_obj_t *ui_Home_Header_Logo;
lv_obj_t *ui_Home_Container_2;
lv_obj_t *ui_Home_Header_Cloud_Status_Icon;
lv_obj_t *ui_Home_Header_Cloud_Status_Label;
lv_obj_t *ui_Home_Container_3;
lv_obj_t *ui_Home_Content_Ip;
lv_obj_t *ui_Home_Content_Mac;
lv_obj_t *ui_Divider;
lv_obj_t *ui_Status_Area;
lv_obj_t *ui_USB_Status1;
lv_obj_t *ui_USB_Inidicator;
lv_obj_t *ui_Home_Footer_Usb_Icon;
lv_obj_t *ui_Home_Footer_Usb_Icon_Label;
lv_obj_t *ui_Home_Footer_Usb_Status_Label;
lv_obj_t *ui_HDMI_Status;
lv_obj_t *ui_HDMI_Indicator;
lv_obj_t *ui_Home_Footer_Hdmi_Icon;
lv_obj_t *ui_Home_Footer_Hdmi_Icon_Label;
lv_obj_t *ui_Home_Footer_Hdmi_Status_Label;


// SCREEN: ui_Manual_Dhcp_Wizard_Screen
void ui_Manual_Dhcp_Wizard_Screen_screen_init(void);
void ui_event_Manual_Dhcp_Wizard_Screen( lv_event_t * e);
lv_obj_t *ui_Manual_Dhcp_Wizard_Screen;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_0;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_1;
lv_obj_t *ui_Manual_Dhcp_Wizard_Header_IP_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Header_IP_Type;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_2;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_3;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_4;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_1;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_2;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_3;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_5;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_4;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_5;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_6;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_6;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_7;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_8;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_9;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_7;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_10;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_11;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_12;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Container_8;
void ui_event_Manual_Dhcp_Wizard_Content_Number_Button_Cancel( lv_event_t * e);
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm;
lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label;


// SCREEN: ui_Status_Screen
void ui_Status_Screen_screen_init(void);
void ui_event_Status_Screen( lv_event_t * e);
lv_obj_t *ui_Status_Screen;
lv_obj_t *ui_Status_Container_0;
lv_obj_t *ui_Status_Container_1;
void ui_event_Status_Header_Back_Button( lv_event_t * e);
lv_obj_t *ui_Status_Header_Back_Button;
lv_obj_t *ui_Status_Header_Back_Button_Icon;
lv_obj_t *ui_Status_Header_Page_Name_Label;
lv_obj_t *ui_Status_Container_2;
lv_obj_t *ui_Status_Content_Device_Id_Headline_Label;
lv_obj_t *ui_Status_Content_Device_Id_Content_Label;
lv_obj_t *ui_Status_Container_3;
lv_obj_t *ui_Status_Content_Cloud_Account_Id_Headline_Label;
lv_obj_t *ui_Status_Content_Cloud_Account_Id_Content_Label;


// SCREEN: ui_About_Screen
void ui_About_Screen_screen_init(void);
void ui_event_About_Screen( lv_event_t * e);
lv_obj_t *ui_About_Screen;
lv_obj_t *ui_About_Container_0;
lv_obj_t *ui_About_Container_1;
void ui_event_About_Header_Back_Button( lv_event_t * e);
lv_obj_t *ui_About_Header_Back_Button;
lv_obj_t *ui_About_Header_Back_Button_Icon;
lv_obj_t *ui_About_Header_Page_Name_Label;
lv_obj_t *ui_About_Container_2;
lv_obj_t *ui_About_Content_Operating_System_Version_Headline_Label;
lv_obj_t *ui_About_Content_Operating_System_Version_ContentLabel;
lv_obj_t *ui_About_Container_3;
lv_obj_t *ui_About_Content_App_Version_Headline_Label;
lv_obj_t *ui_About_Content_App_Version_Content_Label;


// SCREEN: ui_Reset_Device_Screen
void ui_Reset_Device_Screen_screen_init(void);
void ui_event_Reset_Device_Screen( lv_event_t * e);
lv_obj_t *ui_Reset_Device_Screen;
lv_obj_t *ui_Reset_Container_0;
lv_obj_t *ui_Reset_Container_1;
void ui_event_Reset_Device_Header_Back_Button( lv_event_t * e);
lv_obj_t *ui_Reset_Device_Header_Back_Button;
lv_obj_t *ui_Reset_Device_Header_Back_Button_Icon;
lv_obj_t *ui_Reset_Device_Header_Page_Name_Label;
lv_obj_t *ui_Reset_Container_2;
lv_obj_t *ui_Reset_Content_Headline_Label;
lv_obj_t *ui_Reset_Content_Button;
lv_obj_t *ui_Reset_Content_Button_Label;


// SCREEN: ui_Network_Screen
void ui_Network_Screen_screen_init(void);
void ui_event_Network_Screen( lv_event_t * e);
lv_obj_t *ui_Network_Screen;
lv_obj_t *ui_Network_Container_0;
lv_obj_t *ui_Network_Container_1;
void ui_event_Network_Header_Back_Button( lv_event_t * e);
lv_obj_t *ui_Network_Header_Back_Button;
lv_obj_t *ui_Network_Header_Back_Button_Icon;
lv_obj_t *ui_Network_Header_Page_Name_Label;
lv_obj_t *ui_Network_Content_Section_Headline;
lv_obj_t *ui_Network_Container_2;
lv_obj_t *ui_Network_Content_IP_Automatic_Button;
lv_obj_t *ui_Network_Content_IP_Automatic_Button_Label;
lv_obj_t *ui_Network_Content_IP_Automatic_Button_Checkbox_Icon;
lv_obj_t *ui_Network_Content_IP_Divider;
lv_obj_t *ui_Network_Content_IP_Manual_Button;
lv_obj_t *ui_Network_Content_IP_Manual_Button_Label;
lv_obj_t *ui_Network_Content_IP_Manual_Button_Checkbox_Icon;
void ui_event_Network_Content_Configure_Manually_Button( lv_event_t * e);
lv_obj_t *ui_Network_Content_Configure_Manually_Button;
lv_obj_t *ui_Network_Content_Configure_Manually_Button_Label;


// SCREEN: ui_Network_Setup_Failed_Screen
void ui_Network_Setup_Failed_Screen_screen_init(void);
void ui_event_Network_Setup_Failed_Screen( lv_event_t * e);
lv_obj_t *ui_Network_Setup_Failed_Screen;
lv_obj_t *ui_Network_Setup_Failed_Container_0;
lv_obj_t *ui_Network_Setup_Failed_Container_1;
lv_obj_t *ui_Network_Setup_Failed_Header_Logo;
lv_obj_t *ui_Network_Setup_Failed_Container_2;
lv_obj_t *ui_Network_Setup_Failed_Container_3;
lv_obj_t *ui_Network_Setup_Failed_Container_4;
lv_obj_t *ui_Network_Setup_Failed_Content_Headline;
lv_obj_t *ui_Network_Setup_Failed_Content_Sub_Title;
void ui_event_Network_Setup_Failed_Content_Button( lv_event_t * e);
lv_obj_t *ui_Network_Setup_Failed_Content_Button;
lv_obj_t *ui_Network_Setup_Failed_Content_Button_Label;
lv_obj_t *ui_Network_Setup_Failed_Content_Button_Icon;


// SCREEN: ui_No_Network_Screen
void ui_No_Network_Screen_screen_init(void);
void ui_event_No_Network_Screen( lv_event_t * e);
lv_obj_t *ui_No_Network_Screen;
lv_obj_t *ui_No_Network_Container_0;
lv_obj_t *ui_No_Network_Container_1;
lv_obj_t *ui_No_Network_Header_Logo;
lv_obj_t *ui_No_Network_Container_2;
lv_obj_t *ui_No_Network_Container_3;
lv_obj_t *ui_No_Network_Container_4;
lv_obj_t *ui_No_Network_Content_Icon;
lv_obj_t *ui_No_Network_Content_Headline;
lv_obj_t *ui_No_Network_Content_Sub_Title;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_386483491[1] = {&ui_img_1796371062};
const lv_img_dsc_t *ui_imgset_d[1] = {&ui_img_d2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Boot_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Settings_Overview_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Home_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_Screen_screen_init);
}
}
void ui_event_Settings_Overview_Header_Back_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_Screen_screen_init);
}
}
void ui_event_Settings_Overview_Network_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESS_LOST) {
      _ui_screen_change( &ui_Network_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Network_Screen_screen_init);
}
}
void ui_event_Settings_Overview_Status_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Status_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Status_Screen_screen_init);
}
}
void ui_event_Settings_Overview_About_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_About_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_About_Screen_screen_init);
}
}
void ui_event_Settings_Overview_Reset_Device_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Reset_Device_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Reset_Device_Screen_screen_init);
}
}
void ui_event_Home_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Manual_Dhcp_Wizard_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Manual_Dhcp_Wizard_Content_Number_Button_Cancel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Network_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Network_Screen_screen_init);
}
}
void ui_event_Status_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Status_Header_Back_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_About_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_About_Header_Back_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Reset_Device_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Reset_Device_Header_Back_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Network_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Network_Header_Back_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Network_Content_Configure_Manually_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Manual_Dhcp_Wizard_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Manual_Dhcp_Wizard_Screen_screen_init);
}
}
void ui_event_Network_Setup_Failed_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Settings_Overview_Screen_screen_init);
}
}
void ui_event_Network_Setup_Failed_Content_Button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Network_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Network_Screen_screen_init);
}
}
void ui_event_No_Network_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Settings_Overview_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Settings_Overview_Screen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_basic_init(dispp);
lv_disp_set_theme(dispp, theme);
ui_Boot_Screen_screen_init();
ui_Settings_Overview_Screen_screen_init();
ui_Home_Screen_screen_init();
ui_Manual_Dhcp_Wizard_Screen_screen_init();
ui_Status_Screen_screen_init();
ui_About_Screen_screen_init();
ui_Reset_Device_Screen_screen_init();
ui_Network_Screen_screen_init();
ui_Network_Setup_Failed_Screen_screen_init();
ui_No_Network_Screen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Boot_Screen);
}
