// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Boot_Screen
void ui_Boot_Screen_screen_init(void);
void ui_event_Boot_Screen( lv_event_t * e);
extern lv_obj_t *ui_Boot_Screen;
extern lv_obj_t *ui_Boot_Container_0;
extern lv_obj_t *ui_Boot_Container_1;
extern lv_obj_t *ui_Boot_Logo;
// SCREEN: ui_Settings_Overview_Screen
void ui_Settings_Overview_Screen_screen_init(void);
void ui_event_Settings_Overview_Screen( lv_event_t * e);
extern lv_obj_t *ui_Settings_Overview_Screen;
extern lv_obj_t *ui_Settings_Overview_Container_0;
extern lv_obj_t *ui_Settings_Overview_Container_1;
void ui_event_Settings_Overview_Header_Back_Button( lv_event_t * e);
extern lv_obj_t *ui_Settings_Overview_Header_Back_Button;
extern lv_obj_t *ui_Settings_Overview_Header_Back_Button_Icon;
extern lv_obj_t *ui_Settings_Overview_Header_Page_Name_Label;
extern lv_obj_t *ui_Settings_Overview_Container_2;
void ui_event_Settings_Overview_Network_Button( lv_event_t * e);
extern lv_obj_t *ui_Settings_Overview_Network_Button;
extern lv_obj_t *ui_Settings_Overview_Network_Button_Label;
void ui_event_Settings_Overview_Status_Button( lv_event_t * e);
extern lv_obj_t *ui_Settings_Overview_Status_Button;
extern lv_obj_t *ui_Settings_Overview_Status_Button_Label;
void ui_event_Settings_Overview_About_Button( lv_event_t * e);
extern lv_obj_t *ui_Settings_Overview_About_Button;
extern lv_obj_t *ui_Settings_Overview_About_Button_Label;
void ui_event_Settings_Overview_Reset_Device_Button( lv_event_t * e);
extern lv_obj_t *ui_Settings_Overview_Reset_Device_Button;
extern lv_obj_t *ui_Settings_Overview_Reset_Device_Button_Label;
// SCREEN: ui_Home_Screen
void ui_Home_Screen_screen_init(void);
void ui_event_Home_Screen( lv_event_t * e);
extern lv_obj_t *ui_Home_Screen;
extern lv_obj_t *ui_Home_Container_0;
extern lv_obj_t *ui_Home_Container_1;
extern lv_obj_t *ui_Home_Header_Logo;
extern lv_obj_t *ui_Home_Container_2;
extern lv_obj_t *ui_Home_Header_Cloud_Status_Icon;
extern lv_obj_t *ui_Home_Header_Cloud_Status_Label;
extern lv_obj_t *ui_Home_Container_3;
extern lv_obj_t *ui_Home_Content_Ip;
extern lv_obj_t *ui_Home_Content_Mac;
extern lv_obj_t *ui_Divider;
extern lv_obj_t *ui_Status_Area;
extern lv_obj_t *ui_USB_Status1;
extern lv_obj_t *ui_USB_Inidicator;
extern lv_obj_t *ui_Home_Footer_Usb_Icon;
extern lv_obj_t *ui_Home_Footer_Usb_Icon_Label;
extern lv_obj_t *ui_Home_Footer_Usb_Status_Label;
extern lv_obj_t *ui_HDMI_Status;
extern lv_obj_t *ui_HDMI_Indicator;
extern lv_obj_t *ui_Home_Footer_Hdmi_Icon;
extern lv_obj_t *ui_Home_Footer_Hdmi_Icon_Label;
extern lv_obj_t *ui_Home_Footer_Hdmi_Status_Label;
// SCREEN: ui_Manual_Dhcp_Wizard_Screen
void ui_Manual_Dhcp_Wizard_Screen_screen_init(void);
void ui_event_Manual_Dhcp_Wizard_Screen( lv_event_t * e);
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Screen;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_0;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_1;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Header_IP_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Header_IP_Type;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_2;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_3;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_4;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_1;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_2;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_3;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_5;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_4;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_5;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_6;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_6;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_7;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_8;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_9;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_7;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_10;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_11;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_12;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Container_8;
void ui_event_Manual_Dhcp_Wizard_Content_Number_Button_Cancel( lv_event_t * e);
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm;
extern lv_obj_t *ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label;
// SCREEN: ui_Status_Screen
void ui_Status_Screen_screen_init(void);
void ui_event_Status_Screen( lv_event_t * e);
extern lv_obj_t *ui_Status_Screen;
extern lv_obj_t *ui_Status_Container_0;
extern lv_obj_t *ui_Status_Container_1;
void ui_event_Status_Header_Back_Button( lv_event_t * e);
extern lv_obj_t *ui_Status_Header_Back_Button;
extern lv_obj_t *ui_Status_Header_Back_Button_Icon;
extern lv_obj_t *ui_Status_Header_Page_Name_Label;
extern lv_obj_t *ui_Status_Container_2;
extern lv_obj_t *ui_Status_Content_Device_Id_Headline_Label;
extern lv_obj_t *ui_Status_Content_Device_Id_Content_Label;
extern lv_obj_t *ui_Status_Container_3;
extern lv_obj_t *ui_Status_Content_Cloud_Account_Id_Headline_Label;
extern lv_obj_t *ui_Status_Content_Cloud_Account_Id_Content_Label;
// SCREEN: ui_About_Screen
void ui_About_Screen_screen_init(void);
void ui_event_About_Screen( lv_event_t * e);
extern lv_obj_t *ui_About_Screen;
extern lv_obj_t *ui_About_Container_0;
extern lv_obj_t *ui_About_Container_1;
void ui_event_About_Header_Back_Button( lv_event_t * e);
extern lv_obj_t *ui_About_Header_Back_Button;
extern lv_obj_t *ui_About_Header_Back_Button_Icon;
extern lv_obj_t *ui_About_Header_Page_Name_Label;
extern lv_obj_t *ui_About_Container_2;
extern lv_obj_t *ui_About_Content_Operating_System_Version_Headline_Label;
extern lv_obj_t *ui_About_Content_Operating_System_Version_ContentLabel;
extern lv_obj_t *ui_About_Container_3;
extern lv_obj_t *ui_About_Content_App_Version_Headline_Label;
extern lv_obj_t *ui_About_Content_App_Version_Content_Label;
// SCREEN: ui_Reset_Device_Screen
void ui_Reset_Device_Screen_screen_init(void);
void ui_event_Reset_Device_Screen( lv_event_t * e);
extern lv_obj_t *ui_Reset_Device_Screen;
extern lv_obj_t *ui_Reset_Container_0;
extern lv_obj_t *ui_Reset_Container_1;
void ui_event_Reset_Device_Header_Back_Button( lv_event_t * e);
extern lv_obj_t *ui_Reset_Device_Header_Back_Button;
extern lv_obj_t *ui_Reset_Device_Header_Back_Button_Icon;
extern lv_obj_t *ui_Reset_Device_Header_Page_Name_Label;
extern lv_obj_t *ui_Reset_Container_2;
extern lv_obj_t *ui_Reset_Content_Headline_Label;
extern lv_obj_t *ui_Reset_Content_Button;
extern lv_obj_t *ui_Reset_Content_Button_Label;
// SCREEN: ui_Network_Screen
void ui_Network_Screen_screen_init(void);
void ui_event_Network_Screen( lv_event_t * e);
extern lv_obj_t *ui_Network_Screen;
extern lv_obj_t *ui_Network_Container_0;
extern lv_obj_t *ui_Network_Container_1;
void ui_event_Network_Header_Back_Button( lv_event_t * e);
extern lv_obj_t *ui_Network_Header_Back_Button;
extern lv_obj_t *ui_Network_Header_Back_Button_Icon;
extern lv_obj_t *ui_Network_Header_Page_Name_Label;
extern lv_obj_t *ui_Network_Content_Section_Headline;
extern lv_obj_t *ui_Network_Container_2;
extern lv_obj_t *ui_Network_Content_IP_Automatic_Button;
extern lv_obj_t *ui_Network_Content_IP_Automatic_Button_Label;
extern lv_obj_t *ui_Network_Content_IP_Automatic_Button_Checkbox_Icon;
extern lv_obj_t *ui_Network_Content_IP_Divider;
extern lv_obj_t *ui_Network_Content_IP_Manual_Button;
extern lv_obj_t *ui_Network_Content_IP_Manual_Button_Label;
extern lv_obj_t *ui_Network_Content_IP_Manual_Button_Checkbox_Icon;
void ui_event_Network_Content_Configure_Manually_Button( lv_event_t * e);
extern lv_obj_t *ui_Network_Content_Configure_Manually_Button;
extern lv_obj_t *ui_Network_Content_Configure_Manually_Button_Label;
// SCREEN: ui_Network_Setup_Failed_Screen
void ui_Network_Setup_Failed_Screen_screen_init(void);
void ui_event_Network_Setup_Failed_Screen( lv_event_t * e);
extern lv_obj_t *ui_Network_Setup_Failed_Screen;
extern lv_obj_t *ui_Network_Setup_Failed_Container_0;
extern lv_obj_t *ui_Network_Setup_Failed_Container_1;
extern lv_obj_t *ui_Network_Setup_Failed_Header_Logo;
extern lv_obj_t *ui_Network_Setup_Failed_Container_2;
extern lv_obj_t *ui_Network_Setup_Failed_Container_3;
extern lv_obj_t *ui_Network_Setup_Failed_Container_4;
extern lv_obj_t *ui_Network_Setup_Failed_Content_Headline;
extern lv_obj_t *ui_Network_Setup_Failed_Content_Sub_Title;
void ui_event_Network_Setup_Failed_Content_Button( lv_event_t * e);
extern lv_obj_t *ui_Network_Setup_Failed_Content_Button;
extern lv_obj_t *ui_Network_Setup_Failed_Content_Button_Label;
extern lv_obj_t *ui_Network_Setup_Failed_Content_Button_Icon;
// SCREEN: ui_No_Network_Screen
void ui_No_Network_Screen_screen_init(void);
void ui_event_No_Network_Screen( lv_event_t * e);
extern lv_obj_t *ui_No_Network_Screen;
extern lv_obj_t *ui_No_Network_Container_0;
extern lv_obj_t *ui_No_Network_Container_1;
extern lv_obj_t *ui_No_Network_Header_Logo;
extern lv_obj_t *ui_No_Network_Container_2;
extern lv_obj_t *ui_No_Network_Container_3;
extern lv_obj_t *ui_No_Network_Container_4;
extern lv_obj_t *ui_No_Network_Content_Icon;
extern lv_obj_t *ui_No_Network_Content_Headline;
extern lv_obj_t *ui_No_Network_Content_Sub_Title;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_1796371062);   // assets/boot-logo-2.png
LV_IMG_DECLARE( ui_img_352891484);   // assets/back-caret.png
LV_IMG_DECLARE( ui_img_jetkvm_png);   // assets/jetkvm.png
LV_IMG_DECLARE( ui_img_cloud_png);   // assets/cloud.png
LV_IMG_DECLARE( ui_img_usb_png);   // assets/usb.png
LV_IMG_DECLARE( ui_img_hdmi_png);   // assets/hdmi.png
LV_IMG_DECLARE( ui_img_1318103182);   // assets/back-icon.png
LV_IMG_DECLARE( ui_img_2138704335);   // assets/x-icon.png
LV_IMG_DECLARE( ui_img_536642073);   // assets/check-icon.png
LV_IMG_DECLARE( ui_img_1582207408);   // assets/arrow-icon.png
LV_IMG_DECLARE( ui_img_ethernet_png);   // assets/ethernet.png
LV_IMG_DECLARE( ui_img_cloud_disconnected_png);   // assets/cloud_disconnected.png
LV_IMG_DECLARE( ui_img_d2_png);   // assets/d2.png


LV_FONT_DECLARE( ui_font_Font_Bold_30);
LV_FONT_DECLARE( ui_font_Font_Book_16);
LV_FONT_DECLARE( ui_font_Font_Book_18);
LV_FONT_DECLARE( ui_font_Font_Book_20);
LV_FONT_DECLARE( ui_font_Font_Book_24);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
