// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Boot_Screen_screen_init(void)
{
ui_Boot_Screen = lv_obj_create(NULL);
lv_obj_add_flag( ui_Boot_Screen, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_flex_flow(ui_Boot_Screen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Boot_Screen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Boot_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Boot_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Boot_Screen, 44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Boot_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Boot_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Boot_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Boot_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Boot_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Boot_Container_0 = lv_obj_create(ui_Boot_Screen);
lv_obj_remove_style_all(ui_Boot_Container_0);
lv_obj_set_width( ui_Boot_Container_0, lv_pct(100));
lv_obj_set_height( ui_Boot_Container_0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Boot_Container_0, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Boot_Container_0,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Boot_Container_0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Boot_Container_0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Boot_Container_0, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Boot_Container_0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Boot_Container_1 = lv_obj_create(ui_Boot_Container_0);
lv_obj_remove_style_all(ui_Boot_Container_1);
lv_obj_set_width( ui_Boot_Container_1, lv_pct(100));
lv_obj_set_flex_grow( ui_Boot_Container_1, 1);
lv_obj_set_x( ui_Boot_Container_1, 19 );
lv_obj_set_y( ui_Boot_Container_1, -5 );
lv_obj_set_align( ui_Boot_Container_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Boot_Container_1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Boot_Container_1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Boot_Container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Boot_Logo = lv_img_create(ui_Boot_Container_1);
lv_img_set_src(ui_Boot_Logo, &ui_img_1796371062);
lv_obj_set_width( ui_Boot_Logo, LV_SIZE_CONTENT);  /// 174
lv_obj_set_height( ui_Boot_Logo, LV_SIZE_CONTENT);   /// 49
lv_obj_set_align( ui_Boot_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Boot_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Boot_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Boot_Screen, ui_event_Boot_Screen, LV_EVENT_ALL, NULL);

}
