// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Home_Screen_screen_init(void)
{
ui_Home_Screen = lv_obj_create(NULL);
lv_obj_add_flag( ui_Home_Screen, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_flex_flow(ui_Home_Screen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Home_Screen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Home_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Home_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Home_Screen, 44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Home_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Home_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Home_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Home_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Home_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Home_Container_0 = lv_obj_create(ui_Home_Screen);
lv_obj_remove_style_all(ui_Home_Container_0);
lv_obj_set_width( ui_Home_Container_0, lv_pct(100));
lv_obj_set_height( ui_Home_Container_0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Home_Container_0, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Home_Container_0,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Home_Container_0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Home_Container_0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Home_Container_0, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Home_Container_0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Home_Container_1 = lv_obj_create(ui_Home_Container_0);
lv_obj_remove_style_all(ui_Home_Container_1);
lv_obj_set_width( ui_Home_Container_1, lv_pct(100));
lv_obj_set_height( ui_Home_Container_1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Home_Container_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Home_Container_1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Home_Container_1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Home_Container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Home_Header_Logo = lv_img_create(ui_Home_Container_1);
lv_img_set_src(ui_Home_Header_Logo, &ui_img_jetkvm_png);
lv_obj_set_width( ui_Home_Header_Logo, LV_SIZE_CONTENT);  /// 116
lv_obj_set_height( ui_Home_Header_Logo, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Home_Header_Logo, -2 );
lv_obj_set_y( ui_Home_Header_Logo, 0 );
lv_obj_set_align( ui_Home_Header_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Home_Header_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Home_Header_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Home_Container_2 = lv_obj_create(ui_Home_Container_1);
lv_obj_remove_style_all(ui_Home_Container_2);
lv_obj_set_width( ui_Home_Container_2, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Home_Container_2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Home_Container_2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Home_Container_2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Home_Container_2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Home_Container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Home_Container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Home_Container_2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Home_Header_Cloud_Status_Icon = lv_img_create(ui_Home_Container_2);
lv_img_set_src(ui_Home_Header_Cloud_Status_Icon, &ui_img_cloud_png);
lv_obj_set_width( ui_Home_Header_Cloud_Status_Icon, 22);
lv_obj_set_height( ui_Home_Header_Cloud_Status_Icon, 22);
lv_obj_set_align( ui_Home_Header_Cloud_Status_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Home_Header_Cloud_Status_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Home_Header_Cloud_Status_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Home_Header_Cloud_Status_Label = lv_label_create(ui_Home_Container_2);
lv_obj_set_width( ui_Home_Header_Cloud_Status_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Home_Header_Cloud_Status_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Home_Header_Cloud_Status_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Home_Header_Cloud_Status_Label,"2 active");
lv_obj_set_style_text_color(ui_Home_Header_Cloud_Status_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Home_Header_Cloud_Status_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Home_Header_Cloud_Status_Label, &ui_font_Font_Book_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Home_Container_3 = lv_obj_create(ui_Home_Container_0);
lv_obj_remove_style_all(ui_Home_Container_3);
lv_obj_set_width( ui_Home_Container_3, lv_pct(100));
lv_obj_set_height( ui_Home_Container_3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_Home_Container_3, 1 );
lv_obj_set_y( ui_Home_Container_3, 20 );
lv_obj_set_align( ui_Home_Container_3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Home_Container_3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Home_Container_3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Home_Container_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Home_Content_Ip = lv_label_create(ui_Home_Container_3);
lv_obj_set_width( ui_Home_Content_Ip, lv_pct(100));
lv_obj_set_height( ui_Home_Content_Ip, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Home_Content_Ip, LV_ALIGN_CENTER );
lv_label_set_text(ui_Home_Content_Ip,"192.168.1.123");
lv_obj_set_style_text_color(ui_Home_Content_Ip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Home_Content_Ip, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Home_Content_Ip, &ui_font_Font_Bold_30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Home_Content_Ip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Home_Content_Ip, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_font(ui_Home_Content_Ip, &ui_font_Font_Bold_30, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_font(ui_Home_Content_Ip, &ui_font_Font_Bold_30, LV_PART_MAIN| LV_STATE_USER_2);

ui_Home_Content_Mac = lv_label_create(ui_Home_Container_3);
lv_obj_set_width( ui_Home_Content_Mac, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Home_Content_Mac, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Home_Content_Mac, LV_ALIGN_CENTER );
lv_label_set_text(ui_Home_Content_Mac,"9a:23:b9:84:ef:20");
lv_obj_set_style_text_color(ui_Home_Content_Mac, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Home_Content_Mac, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Home_Content_Mac, &ui_font_Font_Book_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Divider = lv_obj_create(ui_Home_Screen);
lv_obj_remove_style_all(ui_Divider);
lv_obj_set_height( ui_Divider, 1);
lv_obj_set_width( ui_Divider, lv_pct(100));
lv_obj_set_x( ui_Divider, -57 );
lv_obj_set_y( ui_Divider, 39 );
lv_obj_set_align( ui_Divider, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Divider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Divider, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Divider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Area = lv_obj_create(ui_Home_Screen);
lv_obj_remove_style_all(ui_Status_Area);
lv_obj_set_width( ui_Status_Area, lv_pct(100));
lv_obj_set_height( ui_Status_Area, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Status_Area, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Status_Area,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Status_Area, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Status_Area, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_USB_Status1 = lv_obj_create(ui_Status_Area);
lv_obj_remove_style_all(ui_USB_Status1);
lv_obj_set_width( ui_USB_Status1, lv_pct(50));
lv_obj_set_height( ui_USB_Status1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_USB_Status1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_USB_Status1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_USB_Status1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_USB_Status1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_USB_Status1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_USB_Status1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USB_Inidicator = lv_obj_create(ui_USB_Status1);
lv_obj_remove_style_all(ui_USB_Inidicator);
lv_obj_set_width( ui_USB_Inidicator, lv_pct(100));
lv_obj_set_height( ui_USB_Inidicator, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_USB_Inidicator, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_USB_Inidicator,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_USB_Inidicator, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_USB_Inidicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_USB_Inidicator, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_USB_Inidicator, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Home_Footer_Usb_Icon = lv_img_create(ui_USB_Inidicator);
lv_img_set_src(ui_Home_Footer_Usb_Icon, &ui_img_usb_png);
lv_obj_set_width( ui_Home_Footer_Usb_Icon, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Home_Footer_Usb_Icon, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Home_Footer_Usb_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Home_Footer_Usb_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Home_Footer_Usb_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Home_Footer_Usb_Icon_Label = lv_label_create(ui_USB_Inidicator);
lv_obj_set_width( ui_Home_Footer_Usb_Icon_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Home_Footer_Usb_Icon_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Home_Footer_Usb_Icon_Label, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Home_Footer_Usb_Icon_Label,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Home_Footer_Usb_Icon_Label, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Home_Footer_Usb_Icon_Label,"USB");
lv_obj_set_style_text_color(ui_Home_Footer_Usb_Icon_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Home_Footer_Usb_Icon_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Home_Footer_Usb_Icon_Label, &ui_font_Font_Book_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Home_Footer_Usb_Status_Label = lv_label_create(ui_USB_Status1);
lv_obj_set_width( ui_Home_Footer_Usb_Status_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Home_Footer_Usb_Status_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Home_Footer_Usb_Status_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Home_Footer_Usb_Status_Label,"Connected");
lv_obj_set_style_text_color(ui_Home_Footer_Usb_Status_Label, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Home_Footer_Usb_Status_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Home_Footer_Usb_Status_Label, &ui_font_Font_Book_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Home_Footer_Usb_Status_Label, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Home_Footer_Usb_Status_Label, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_color(ui_Home_Footer_Usb_Status_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_text_opa(ui_Home_Footer_Usb_Status_Label, 255, LV_PART_MAIN| LV_STATE_USER_2);

ui_HDMI_Status = lv_obj_create(ui_Status_Area);
lv_obj_remove_style_all(ui_HDMI_Status);
lv_obj_set_width( ui_HDMI_Status, lv_pct(50));
lv_obj_set_height( ui_HDMI_Status, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_HDMI_Status, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HDMI_Status,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HDMI_Status, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_clear_flag( ui_HDMI_Status, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_HDMI_Status, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_HDMI_Status, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HDMI_Indicator = lv_obj_create(ui_HDMI_Status);
lv_obj_remove_style_all(ui_HDMI_Indicator);
lv_obj_set_width( ui_HDMI_Indicator, lv_pct(100));
lv_obj_set_height( ui_HDMI_Indicator, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_HDMI_Indicator, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HDMI_Indicator,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HDMI_Indicator, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_HDMI_Indicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_HDMI_Indicator, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_HDMI_Indicator, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Home_Footer_Hdmi_Icon = lv_img_create(ui_HDMI_Indicator);
lv_img_set_src(ui_Home_Footer_Hdmi_Icon, &ui_img_hdmi_png);
lv_obj_set_width( ui_Home_Footer_Hdmi_Icon, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Home_Footer_Hdmi_Icon, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Home_Footer_Hdmi_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Home_Footer_Hdmi_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Home_Footer_Hdmi_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Home_Footer_Hdmi_Icon_Label = lv_label_create(ui_HDMI_Indicator);
lv_obj_set_width( ui_Home_Footer_Hdmi_Icon_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Home_Footer_Hdmi_Icon_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Home_Footer_Hdmi_Icon_Label, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Home_Footer_Hdmi_Icon_Label,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Home_Footer_Hdmi_Icon_Label, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Home_Footer_Hdmi_Icon_Label,"HDMI");
lv_obj_set_style_text_color(ui_Home_Footer_Hdmi_Icon_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Home_Footer_Hdmi_Icon_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Home_Footer_Hdmi_Icon_Label, &ui_font_Font_Book_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Home_Footer_Hdmi_Status_Label = lv_label_create(ui_HDMI_Status);
lv_obj_set_width( ui_Home_Footer_Hdmi_Status_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Home_Footer_Hdmi_Status_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Home_Footer_Hdmi_Status_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Home_Footer_Hdmi_Status_Label,"Connected");
lv_obj_set_style_text_color(ui_Home_Footer_Hdmi_Status_Label, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Home_Footer_Hdmi_Status_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Home_Footer_Hdmi_Status_Label, &ui_font_Font_Book_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Home_Footer_Hdmi_Status_Label, lv_color_hex(0x22C55E), LV_PART_MAIN | LV_STATE_USER_1 );
lv_obj_set_style_text_opa(ui_Home_Footer_Hdmi_Status_Label, 255, LV_PART_MAIN| LV_STATE_USER_1);
lv_obj_set_style_text_color(ui_Home_Footer_Hdmi_Status_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_USER_2 );
lv_obj_set_style_text_opa(ui_Home_Footer_Hdmi_Status_Label, 255, LV_PART_MAIN| LV_STATE_USER_2);

lv_obj_add_event_cb(ui_Home_Screen, ui_event_Home_Screen, LV_EVENT_ALL, NULL);

}
