// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Manual_Dhcp_Wizard_Screen_screen_init(void)
{
ui_Manual_Dhcp_Wizard_Screen = lv_obj_create(NULL);
lv_obj_add_flag( ui_Manual_Dhcp_Wizard_Screen, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Screen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Screen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Manual_Dhcp_Wizard_Screen, 36, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Manual_Dhcp_Wizard_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Manual_Dhcp_Wizard_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Manual_Dhcp_Wizard_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Container_0 = lv_obj_create(ui_Manual_Dhcp_Wizard_Screen);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_0);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Container_0, lv_pct(100));
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Container_0, lv_pct(100));
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_0, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_0,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Container_0, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Container_0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Container_1 = lv_obj_create(ui_Manual_Dhcp_Wizard_Container_0);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_1);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Container_1, lv_pct(100));
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Container_1, LV_SIZE_CONTENT);   /// 40
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Manual_Dhcp_Wizard_Header_IP_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Container_1);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Header_IP_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Header_IP_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Header_IP_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Header_IP_Label,"192.168.255.255");
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Header_IP_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Header_IP_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Manual_Dhcp_Wizard_Header_IP_Label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Manual_Dhcp_Wizard_Header_IP_Label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Header_IP_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Header_IP_Type = lv_label_create(ui_Manual_Dhcp_Wizard_Container_1);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Header_IP_Type, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Header_IP_Type, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Header_IP_Type, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Header_IP_Type,"Subnet");
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Header_IP_Type, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Header_IP_Type, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Header_IP_Type, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Container_2 = lv_obj_create(ui_Manual_Dhcp_Wizard_Container_0);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_2);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Container_2, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Container_2, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Container_2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Container_3 = lv_obj_create(ui_Manual_Dhcp_Wizard_Container_2);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_3);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Container_3, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Container_3, 1);
lv_obj_set_x( ui_Manual_Dhcp_Wizard_Container_3, -25 );
lv_obj_set_y( ui_Manual_Dhcp_Wizard_Container_3, -36 );
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Container_3, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Container_3, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Container_4 = lv_obj_create(ui_Manual_Dhcp_Wizard_Container_3);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_4);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Container_4, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Container_4, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Container_4, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Content_Number_Button_1 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_4);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_1, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_1, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_1, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_1, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_1, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_1, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_1);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label,"1");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_1_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_2 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_4);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_2, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_2, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_2, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_2, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_2, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_2, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_2);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label,"2");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_2_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_3 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_4);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_3, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_3, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_3, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_3, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_3, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_3, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_3);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label,"3");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_3_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Container_5 = lv_obj_create(ui_Manual_Dhcp_Wizard_Container_3);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_5);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Container_5, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Container_5, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Container_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Container_5, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Content_Number_Button_4 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_5);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_4, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_4, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_4, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_4, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_4, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_4, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_4, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_4, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_4);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label,"4");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_4_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_5 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_5);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_5, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_5, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_5, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_5, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_5, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_5, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_5, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_5, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_5);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label,"5");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_5_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_6 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_5);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_6, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_6, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_6, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_6, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_6, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_6, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_6, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_6, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_6);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label,"6");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_6_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Container_6 = lv_obj_create(ui_Manual_Dhcp_Wizard_Container_3);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_6);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Container_6, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Container_6, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Container_6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Container_6, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Content_Number_Button_7 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_6);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_7, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_7, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_7, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_7, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_7, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_7, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_7, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_7, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_7);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label,"7");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_7_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_8 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_6);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_8, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_8, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_8, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_8, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_8, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_8, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_8, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_8, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_8);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label,"8");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_8_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_9 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_6);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_9, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_9, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_9, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_9, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_9, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_9, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_9, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_9, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_9);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label,"9");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_9_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Container_7 = lv_obj_create(ui_Manual_Dhcp_Wizard_Container_3);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_7);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Container_7, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Container_7, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Container_7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Container_7, 7, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Content_Number_Button_10 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_7);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_10, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_10, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_10, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_10, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_10, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_10, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_10, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_10, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_10);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label,".");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_10_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_11 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_7);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_11, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_11, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_11, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_11, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_11, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_11, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_11, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_11, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label = lv_label_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_11);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label, LV_SIZE_CONTENT);  /// 0
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label,"0");
lv_obj_set_style_text_font(ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_11_Label, 0, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_12 = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_7);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_12, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_12, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_12, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_12, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_12, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_12, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_12, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_12, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label = lv_img_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_12);
lv_img_set_src(ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label, &ui_img_1318103182);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label, LV_SIZE_CONTENT);  /// 17
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label, LV_SIZE_CONTENT);   /// 17
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Content_Number_Button_12_Label, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Manual_Dhcp_Wizard_Container_8 = lv_obj_create(ui_Manual_Dhcp_Wizard_Container_2);
lv_obj_remove_style_all(ui_Manual_Dhcp_Wizard_Container_8);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Container_8, 52);
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Container_8, lv_pct(100));
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Container_8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Manual_Dhcp_Wizard_Container_8,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Manual_Dhcp_Wizard_Container_8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Container_8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Manual_Dhcp_Wizard_Container_8, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Manual_Dhcp_Wizard_Container_8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_8);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label = lv_img_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel);
lv_img_set_src(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label, &ui_img_2138704335);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel_Label, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm = lv_btn_create(ui_Manual_Dhcp_Wizard_Container_8);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, lv_pct(100));
lv_obj_set_flex_grow( ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, 1);
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label = lv_img_create(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm);
lv_img_set_src(ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label, &ui_img_536642073);
lv_obj_set_width( ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label, LV_SIZE_CONTENT);  /// 19
lv_obj_set_height( ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label, LV_SIZE_CONTENT);   /// 14
lv_obj_set_align( ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Manual_Dhcp_Wizard_Content_Number_Button_Confirm_Label, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, ui_event_Manual_Dhcp_Wizard_Content_Number_Button_Cancel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Manual_Dhcp_Wizard_Screen, ui_event_Manual_Dhcp_Wizard_Screen, LV_EVENT_ALL, NULL);

}
