// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_No_Network_Screen_screen_init(void)
{
ui_No_Network_Screen = lv_obj_create(NULL);
lv_obj_add_flag( ui_No_Network_Screen, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_flex_flow(ui_No_Network_Screen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_No_Network_Screen, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_No_Network_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_No_Network_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_No_Network_Screen, 44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_No_Network_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_No_Network_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_No_Network_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_No_Network_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_No_Network_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_No_Network_Container_0 = lv_obj_create(ui_No_Network_Screen);
lv_obj_remove_style_all(ui_No_Network_Container_0);
lv_obj_set_width( ui_No_Network_Container_0, lv_pct(100));
lv_obj_set_flex_grow( ui_No_Network_Container_0, 1);
lv_obj_set_align( ui_No_Network_Container_0, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_No_Network_Container_0,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_No_Network_Container_0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_No_Network_Container_0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_No_Network_Container_0, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_No_Network_Container_0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_No_Network_Container_1 = lv_obj_create(ui_No_Network_Container_0);
lv_obj_remove_style_all(ui_No_Network_Container_1);
lv_obj_set_width( ui_No_Network_Container_1, lv_pct(100));
lv_obj_set_height( ui_No_Network_Container_1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_No_Network_Container_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_No_Network_Container_1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_No_Network_Container_1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_No_Network_Container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_No_Network_Header_Logo = lv_img_create(ui_No_Network_Container_1);
lv_img_set_src(ui_No_Network_Header_Logo, &ui_img_jetkvm_png);
lv_obj_set_width( ui_No_Network_Header_Logo, LV_SIZE_CONTENT);  /// 116
lv_obj_set_height( ui_No_Network_Header_Logo, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_No_Network_Header_Logo, -2 );
lv_obj_set_y( ui_No_Network_Header_Logo, 0 );
lv_obj_set_align( ui_No_Network_Header_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_No_Network_Header_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_No_Network_Header_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_No_Network_Container_2 = lv_obj_create(ui_No_Network_Container_0);
lv_obj_remove_style_all(ui_No_Network_Container_2);
lv_obj_set_width( ui_No_Network_Container_2, lv_pct(100));
lv_obj_set_flex_grow( ui_No_Network_Container_2, 1);
lv_obj_set_x( ui_No_Network_Container_2, 1 );
lv_obj_set_y( ui_No_Network_Container_2, 20 );
lv_obj_set_align( ui_No_Network_Container_2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_No_Network_Container_2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_No_Network_Container_2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_No_Network_Container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_No_Network_Container_3 = lv_obj_create(ui_No_Network_Container_2);
lv_obj_remove_style_all(ui_No_Network_Container_3);
lv_obj_set_width( ui_No_Network_Container_3, lv_pct(100));
lv_obj_set_flex_grow( ui_No_Network_Container_3, 1);
lv_obj_set_align( ui_No_Network_Container_3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_No_Network_Container_3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_No_Network_Container_3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_No_Network_Container_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_No_Network_Container_4 = lv_obj_create(ui_No_Network_Container_3);
lv_obj_remove_style_all(ui_No_Network_Container_4);
lv_obj_set_width( ui_No_Network_Container_4, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_No_Network_Container_4, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_No_Network_Container_4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_No_Network_Container_4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_No_Network_Container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_No_Network_Container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_No_Network_Container_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_No_Network_Container_4, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_No_Network_Content_Icon = lv_img_create(ui_No_Network_Container_4);
lv_img_set_src(ui_No_Network_Content_Icon, &ui_img_ethernet_png);
lv_obj_set_width( ui_No_Network_Content_Icon, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_No_Network_Content_Icon, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_No_Network_Content_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_No_Network_Content_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_No_Network_Content_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_No_Network_Content_Headline = lv_label_create(ui_No_Network_Container_3);
lv_obj_set_width( ui_No_Network_Content_Headline, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_No_Network_Content_Headline, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_No_Network_Content_Headline, LV_ALIGN_CENTER );
lv_label_set_text(ui_No_Network_Content_Headline,"No Network");
lv_obj_set_style_text_color(ui_No_Network_Content_Headline, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_No_Network_Content_Headline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_No_Network_Content_Headline, &ui_font_Font_Bold_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_No_Network_Content_Sub_Title = lv_label_create(ui_No_Network_Container_3);
lv_obj_set_width( ui_No_Network_Content_Sub_Title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_No_Network_Content_Sub_Title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_No_Network_Content_Sub_Title, LV_ALIGN_CENTER );
lv_label_set_text(ui_No_Network_Content_Sub_Title,"Connect Ethernet cable");
lv_obj_set_style_text_color(ui_No_Network_Content_Sub_Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_No_Network_Content_Sub_Title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_No_Network_Content_Sub_Title, &ui_font_Font_Book_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_No_Network_Screen, ui_event_No_Network_Screen, LV_EVENT_ALL, NULL);

}
