// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Network_Screen_screen_init(void)
{
ui_Network_Screen = lv_obj_create(NULL);
lv_obj_add_flag( ui_Network_Screen, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_flex_flow(ui_Network_Screen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Network_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Network_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Network_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Network_Screen, 44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Network_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Network_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Network_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Network_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Network_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Container_0 = lv_obj_create(ui_Network_Screen);
lv_obj_remove_style_all(ui_Network_Container_0);
lv_obj_set_width( ui_Network_Container_0, lv_pct(100));
lv_obj_set_height( ui_Network_Container_0, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Network_Container_0, 75 );
lv_obj_set_y( ui_Network_Container_0, -33 );
lv_obj_set_align( ui_Network_Container_0, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Network_Container_0,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Network_Container_0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Network_Container_0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Network_Container_0, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Network_Container_0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Container_1 = lv_obj_create(ui_Network_Container_0);
lv_obj_remove_style_all(ui_Network_Container_1);
lv_obj_set_width( ui_Network_Container_1, lv_pct(100));
lv_obj_set_height( ui_Network_Container_1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Network_Container_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Network_Container_1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Network_Container_1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Network_Container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Network_Header_Back_Button = lv_btn_create(ui_Network_Container_1);
lv_obj_set_width( ui_Network_Header_Back_Button, 32);
lv_obj_set_height( ui_Network_Header_Back_Button, 32);
lv_obj_set_align( ui_Network_Header_Back_Button, LV_ALIGN_CENTER );
lv_obj_add_state( ui_Network_Header_Back_Button, LV_STATE_PRESSED );     /// States
lv_obj_set_style_radius(ui_Network_Header_Back_Button, 10000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Network_Header_Back_Button, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Network_Header_Back_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Network_Header_Back_Button, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Network_Header_Back_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Network_Header_Back_Button_Icon = lv_img_create(ui_Network_Header_Back_Button);
lv_img_set_src(ui_Network_Header_Back_Button_Icon, &ui_img_352891484);
lv_obj_set_width( ui_Network_Header_Back_Button_Icon, LV_SIZE_CONTENT);  /// 8
lv_obj_set_height( ui_Network_Header_Back_Button_Icon, LV_SIZE_CONTENT);   /// 12
lv_obj_set_align( ui_Network_Header_Back_Button_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Network_Header_Back_Button_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Network_Header_Back_Button_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Network_Header_Page_Name_Label = lv_label_create(ui_Network_Container_1);
lv_obj_set_width( ui_Network_Header_Page_Name_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Network_Header_Page_Name_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Network_Header_Page_Name_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Network_Header_Page_Name_Label,"Network");
lv_obj_set_style_text_color(ui_Network_Header_Page_Name_Label, lv_color_hex(0x1D4ED8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Network_Header_Page_Name_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Network_Header_Page_Name_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Content_Section_Headline = lv_label_create(ui_Network_Screen);
lv_obj_set_width( ui_Network_Content_Section_Headline, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Network_Content_Section_Headline, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Network_Content_Section_Headline, LV_ALIGN_CENTER );
lv_label_set_text(ui_Network_Content_Section_Headline,"IPv4 Settings");
lv_obj_set_style_text_color(ui_Network_Content_Section_Headline, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Network_Content_Section_Headline, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Network_Content_Section_Headline, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Container_2 = lv_obj_create(ui_Network_Screen);
lv_obj_remove_style_all(ui_Network_Container_2);
lv_obj_set_width( ui_Network_Container_2, lv_pct(100));
lv_obj_set_height( ui_Network_Container_2, LV_SIZE_CONTENT);   /// 500
lv_obj_set_align( ui_Network_Container_2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Network_Container_2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Network_Container_2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Network_Container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Network_Container_2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_clip_corner(ui_Network_Container_2, true, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Network_Container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Network_Container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Content_IP_Automatic_Button = lv_btn_create(ui_Network_Container_2);
lv_obj_set_width( ui_Network_Content_IP_Automatic_Button, lv_pct(100));
lv_obj_set_height( ui_Network_Content_IP_Automatic_Button, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Network_Content_IP_Automatic_Button, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Network_Content_IP_Automatic_Button,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Network_Content_IP_Automatic_Button, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_radius(ui_Network_Content_IP_Automatic_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Network_Content_IP_Automatic_Button, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Network_Content_IP_Automatic_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Network_Content_IP_Automatic_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Network_Content_IP_Automatic_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Network_Content_IP_Automatic_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Network_Content_IP_Automatic_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Network_Content_IP_Automatic_Button, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Network_Content_IP_Automatic_Button, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Network_Content_IP_Automatic_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Network_Content_IP_Automatic_Button_Label = lv_label_create(ui_Network_Content_IP_Automatic_Button);
lv_obj_set_width( ui_Network_Content_IP_Automatic_Button_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Network_Content_IP_Automatic_Button_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Network_Content_IP_Automatic_Button_Label, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Network_Content_IP_Automatic_Button_Label,"Automatic");
lv_obj_set_style_text_color(ui_Network_Content_IP_Automatic_Button_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Network_Content_IP_Automatic_Button_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Network_Content_IP_Automatic_Button_Label, &ui_font_Font_Book_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Content_IP_Automatic_Button_Checkbox_Icon = lv_obj_create(ui_Network_Content_IP_Automatic_Button);
lv_obj_remove_style_all(ui_Network_Content_IP_Automatic_Button_Checkbox_Icon);
lv_obj_set_width( ui_Network_Content_IP_Automatic_Button_Checkbox_Icon, 19);
lv_obj_set_height( ui_Network_Content_IP_Automatic_Button_Checkbox_Icon, 14);
lv_obj_set_align( ui_Network_Content_IP_Automatic_Button_Checkbox_Icon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Network_Content_IP_Automatic_Button_Checkbox_Icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Network_Content_IP_Automatic_Button_Checkbox_Icon, &ui_img_536642073, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_opa(ui_Network_Content_IP_Automatic_Button_Checkbox_Icon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Content_IP_Divider = lv_obj_create(ui_Network_Container_2);
lv_obj_remove_style_all(ui_Network_Content_IP_Divider);
lv_obj_set_height( ui_Network_Content_IP_Divider, 1);
lv_obj_set_width( ui_Network_Content_IP_Divider, lv_pct(100));
lv_obj_set_align( ui_Network_Content_IP_Divider, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Network_Content_IP_Divider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Network_Content_IP_Divider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Network_Content_IP_Divider, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Content_IP_Manual_Button = lv_btn_create(ui_Network_Container_2);
lv_obj_set_width( ui_Network_Content_IP_Manual_Button, lv_pct(100));
lv_obj_set_height( ui_Network_Content_IP_Manual_Button, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Network_Content_IP_Manual_Button, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Network_Content_IP_Manual_Button,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Network_Content_IP_Manual_Button, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_set_style_radius(ui_Network_Content_IP_Manual_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Network_Content_IP_Manual_Button, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Network_Content_IP_Manual_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Network_Content_IP_Manual_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Network_Content_IP_Manual_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Network_Content_IP_Manual_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Network_Content_IP_Manual_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Network_Content_IP_Manual_Button, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Network_Content_IP_Manual_Button, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Network_Content_IP_Manual_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Network_Content_IP_Manual_Button_Label = lv_label_create(ui_Network_Content_IP_Manual_Button);
lv_obj_set_width( ui_Network_Content_IP_Manual_Button_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Network_Content_IP_Manual_Button_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Network_Content_IP_Manual_Button_Label, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Network_Content_IP_Manual_Button_Label,"Manual");
lv_obj_set_style_text_color(ui_Network_Content_IP_Manual_Button_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Network_Content_IP_Manual_Button_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Network_Content_IP_Manual_Button_Label, &ui_font_Font_Book_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Network_Content_IP_Manual_Button_Checkbox_Icon = lv_obj_create(ui_Network_Content_IP_Manual_Button);
lv_obj_remove_style_all(ui_Network_Content_IP_Manual_Button_Checkbox_Icon);
lv_obj_set_width( ui_Network_Content_IP_Manual_Button_Checkbox_Icon, 19);
lv_obj_set_height( ui_Network_Content_IP_Manual_Button_Checkbox_Icon, 14);
lv_obj_set_align( ui_Network_Content_IP_Manual_Button_Checkbox_Icon, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Network_Content_IP_Manual_Button_Checkbox_Icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Network_Content_IP_Manual_Button_Checkbox_Icon, &ui_img_536642073, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Network_Content_Configure_Manually_Button = lv_btn_create(ui_Network_Screen);
lv_obj_set_width( ui_Network_Content_Configure_Manually_Button, lv_pct(100));
lv_obj_set_height( ui_Network_Content_Configure_Manually_Button, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Network_Content_Configure_Manually_Button, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Network_Content_Configure_Manually_Button, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Network_Content_Configure_Manually_Button, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Network_Content_Configure_Manually_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Network_Content_Configure_Manually_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Network_Content_Configure_Manually_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Network_Content_Configure_Manually_Button, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Network_Content_Configure_Manually_Button, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Network_Content_Configure_Manually_Button, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Network_Content_Configure_Manually_Button, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Network_Content_Configure_Manually_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Network_Content_Configure_Manually_Button_Label = lv_label_create(ui_Network_Content_Configure_Manually_Button);
lv_obj_set_width( ui_Network_Content_Configure_Manually_Button_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Network_Content_Configure_Manually_Button_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Network_Content_Configure_Manually_Button_Label, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Network_Content_Configure_Manually_Button_Label,"Configure IPv4");
lv_obj_set_style_text_color(ui_Network_Content_Configure_Manually_Button_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Network_Content_Configure_Manually_Button_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Network_Content_Configure_Manually_Button_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Network_Header_Back_Button, ui_event_Network_Header_Back_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Network_Content_Configure_Manually_Button, ui_event_Network_Content_Configure_Manually_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Network_Screen, ui_event_Network_Screen, LV_EVENT_ALL, NULL);

}
