// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Reset_Device_Screen_screen_init(void)
{
ui_Reset_Device_Screen = lv_obj_create(NULL);
lv_obj_add_flag( ui_Reset_Device_Screen, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_flex_flow(ui_Reset_Device_Screen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Reset_Device_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Reset_Device_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Reset_Device_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Reset_Device_Screen, 44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Reset_Device_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Reset_Device_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Reset_Device_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Reset_Device_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Reset_Device_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Reset_Container_0 = lv_obj_create(ui_Reset_Device_Screen);
lv_obj_remove_style_all(ui_Reset_Container_0);
lv_obj_set_width( ui_Reset_Container_0, lv_pct(100));
lv_obj_set_height( ui_Reset_Container_0, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Reset_Container_0, 75 );
lv_obj_set_y( ui_Reset_Container_0, -33 );
lv_obj_set_align( ui_Reset_Container_0, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Reset_Container_0,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Reset_Container_0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Reset_Container_0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Reset_Container_0, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Reset_Container_0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Reset_Container_1 = lv_obj_create(ui_Reset_Container_0);
lv_obj_remove_style_all(ui_Reset_Container_1);
lv_obj_set_width( ui_Reset_Container_1, lv_pct(100));
lv_obj_set_height( ui_Reset_Container_1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Reset_Container_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Reset_Container_1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Reset_Container_1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Reset_Container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Reset_Device_Header_Back_Button = lv_btn_create(ui_Reset_Container_1);
lv_obj_set_width( ui_Reset_Device_Header_Back_Button, 32);
lv_obj_set_height( ui_Reset_Device_Header_Back_Button, 32);
lv_obj_set_align( ui_Reset_Device_Header_Back_Button, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Reset_Device_Header_Back_Button, 10000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Reset_Device_Header_Back_Button, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Reset_Device_Header_Back_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Reset_Device_Header_Back_Button, 10000, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Reset_Device_Header_Back_Button, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Reset_Device_Header_Back_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Reset_Device_Header_Back_Button_Icon = lv_img_create(ui_Reset_Device_Header_Back_Button);
lv_img_set_src(ui_Reset_Device_Header_Back_Button_Icon, &ui_img_352891484);
lv_obj_set_width( ui_Reset_Device_Header_Back_Button_Icon, LV_SIZE_CONTENT);  /// 8
lv_obj_set_height( ui_Reset_Device_Header_Back_Button_Icon, LV_SIZE_CONTENT);   /// 12
lv_obj_set_align( ui_Reset_Device_Header_Back_Button_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Reset_Device_Header_Back_Button_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Reset_Device_Header_Back_Button_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Reset_Device_Header_Page_Name_Label = lv_label_create(ui_Reset_Container_1);
lv_obj_set_width( ui_Reset_Device_Header_Page_Name_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Reset_Device_Header_Page_Name_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Reset_Device_Header_Page_Name_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Reset_Device_Header_Page_Name_Label,"Reset Device");
lv_obj_set_style_text_color(ui_Reset_Device_Header_Page_Name_Label, lv_color_hex(0x1D4ED8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Reset_Device_Header_Page_Name_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Reset_Device_Header_Page_Name_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Reset_Container_2 = lv_obj_create(ui_Reset_Device_Screen);
lv_obj_remove_style_all(ui_Reset_Container_2);
lv_obj_set_width( ui_Reset_Container_2, lv_pct(100));
lv_obj_set_flex_grow( ui_Reset_Container_2, 1);
lv_obj_set_align( ui_Reset_Container_2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Reset_Container_2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Reset_Container_2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Reset_Container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Reset_Container_2, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Reset_Container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Reset_Content_Headline_Label = lv_label_create(ui_Reset_Container_2);
lv_obj_set_width( ui_Reset_Content_Headline_Label, lv_pct(100));
lv_obj_set_height( ui_Reset_Content_Headline_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Reset_Content_Headline_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Reset_Content_Headline_Label,"Press and hold for\n20 seconds");
lv_obj_set_style_text_color(ui_Reset_Content_Headline_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Reset_Content_Headline_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Reset_Content_Headline_Label, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Reset_Content_Headline_Label, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Reset_Content_Headline_Label, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Reset_Content_Headline_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Reset_Content_Button = lv_btn_create(ui_Reset_Container_2);
lv_obj_set_height( ui_Reset_Content_Button, 54);
lv_obj_set_width( ui_Reset_Content_Button, lv_pct(100));
lv_obj_set_align( ui_Reset_Content_Button, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Reset_Content_Button, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Reset_Content_Button, lv_color_hex(0xDC2626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Reset_Content_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Reset_Content_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Reset_Content_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Reset_Content_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Reset_Content_Button, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Reset_Content_Button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Reset_Content_Button, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Reset_Content_Button, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Reset_Content_Button, 8, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_Reset_Content_Button, lv_color_hex(0xEF2A2A), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Reset_Content_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_color(ui_Reset_Content_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_border_opa(ui_Reset_Content_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_border_width(ui_Reset_Content_Button, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_pad_left(ui_Reset_Content_Button, 16, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_pad_right(ui_Reset_Content_Button, 0, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_pad_top(ui_Reset_Content_Button, 20, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_pad_bottom(ui_Reset_Content_Button, 20, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Reset_Content_Button_Label = lv_label_create(ui_Reset_Content_Button);
lv_obj_set_width( ui_Reset_Content_Button_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Reset_Content_Button_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Reset_Content_Button_Label, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Reset_Content_Button_Label,"Hold to reset");
lv_obj_set_style_text_color(ui_Reset_Content_Button_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Reset_Content_Button_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Reset_Content_Button_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Reset_Device_Header_Back_Button, ui_event_Reset_Device_Header_Back_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Reset_Device_Screen, ui_event_Reset_Device_Screen, LV_EVENT_ALL, NULL);

}
