// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Status_Screen_screen_init(void)
{
ui_Status_Screen = lv_obj_create(NULL);
lv_obj_add_flag( ui_Status_Screen, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_set_flex_flow(ui_Status_Screen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Status_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Status_Screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Status_Screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Status_Screen, 44, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Status_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Status_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Status_Screen, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Status_Screen, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Status_Screen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Container_0 = lv_obj_create(ui_Status_Screen);
lv_obj_remove_style_all(ui_Status_Container_0);
lv_obj_set_width( ui_Status_Container_0, lv_pct(100));
lv_obj_set_height( ui_Status_Container_0, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Status_Container_0, 75 );
lv_obj_set_y( ui_Status_Container_0, -33 );
lv_obj_set_align( ui_Status_Container_0, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Status_Container_0,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Status_Container_0, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Status_Container_0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Status_Container_0, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Status_Container_0, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Container_1 = lv_obj_create(ui_Status_Container_0);
lv_obj_remove_style_all(ui_Status_Container_1);
lv_obj_set_width( ui_Status_Container_1, lv_pct(100));
lv_obj_set_height( ui_Status_Container_1, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Status_Container_1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Status_Container_1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Status_Container_1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Status_Container_1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Status_Header_Back_Button = lv_btn_create(ui_Status_Container_1);
lv_obj_set_width( ui_Status_Header_Back_Button, 32);
lv_obj_set_height( ui_Status_Header_Back_Button, 32);
lv_obj_set_align( ui_Status_Header_Back_Button, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Status_Header_Back_Button, 10000, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Status_Header_Back_Button, lv_color_hex(0x262626), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Status_Header_Back_Button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Status_Header_Back_Button, lv_color_hex(0x2E2E2E), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Status_Header_Back_Button, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Status_Header_Back_Button_Icon = lv_img_create(ui_Status_Header_Back_Button);
lv_img_set_src(ui_Status_Header_Back_Button_Icon, &ui_img_352891484);
lv_obj_set_width( ui_Status_Header_Back_Button_Icon, LV_SIZE_CONTENT);  /// 8
lv_obj_set_height( ui_Status_Header_Back_Button_Icon, LV_SIZE_CONTENT);   /// 12
lv_obj_set_align( ui_Status_Header_Back_Button_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Status_Header_Back_Button_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Status_Header_Back_Button_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Status_Header_Page_Name_Label = lv_label_create(ui_Status_Container_1);
lv_obj_set_width( ui_Status_Header_Page_Name_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Status_Header_Page_Name_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Status_Header_Page_Name_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Status_Header_Page_Name_Label,"Status");
lv_obj_set_style_text_color(ui_Status_Header_Page_Name_Label, lv_color_hex(0x1D4ED8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Status_Header_Page_Name_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Status_Header_Page_Name_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Container_2 = lv_obj_create(ui_Status_Screen);
lv_obj_remove_style_all(ui_Status_Container_2);
lv_obj_set_width( ui_Status_Container_2, lv_pct(100));
lv_obj_set_height( ui_Status_Container_2, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Status_Container_2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Status_Container_2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Status_Container_2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Status_Container_2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Status_Container_2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Status_Container_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Content_Device_Id_Headline_Label = lv_label_create(ui_Status_Container_2);
lv_obj_set_width( ui_Status_Content_Device_Id_Headline_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Status_Content_Device_Id_Headline_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Status_Content_Device_Id_Headline_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Status_Content_Device_Id_Headline_Label,"Device ID");
lv_obj_set_style_text_color(ui_Status_Content_Device_Id_Headline_Label, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Status_Content_Device_Id_Headline_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Status_Content_Device_Id_Headline_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Content_Device_Id_Content_Label = lv_label_create(ui_Status_Container_2);
lv_obj_set_width( ui_Status_Content_Device_Id_Content_Label, lv_pct(100));
lv_obj_set_height( ui_Status_Content_Device_Id_Content_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Status_Content_Device_Id_Content_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Status_Content_Device_Id_Content_Label,"64238c05ececc831-102F271723");
lv_obj_set_style_text_color(ui_Status_Content_Device_Id_Content_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Status_Content_Device_Id_Content_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Status_Content_Device_Id_Content_Label, &ui_font_Font_Book_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Container_3 = lv_obj_create(ui_Status_Screen);
lv_obj_remove_style_all(ui_Status_Container_3);
lv_obj_set_width( ui_Status_Container_3, lv_pct(100));
lv_obj_set_height( ui_Status_Container_3, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Status_Container_3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Status_Container_3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Status_Container_3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Status_Container_3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Status_Container_3, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Status_Container_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Content_Cloud_Account_Id_Headline_Label = lv_label_create(ui_Status_Container_3);
lv_obj_set_width( ui_Status_Content_Cloud_Account_Id_Headline_Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Status_Content_Cloud_Account_Id_Headline_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Status_Content_Cloud_Account_Id_Headline_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Status_Content_Cloud_Account_Id_Headline_Label,"Cloud Account ID");
lv_obj_set_style_text_color(ui_Status_Content_Cloud_Account_Id_Headline_Label, lv_color_hex(0x94A3B8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Status_Content_Cloud_Account_Id_Headline_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Status_Content_Cloud_Account_Id_Headline_Label, &ui_font_Font_Book_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Status_Content_Cloud_Account_Id_Content_Label = lv_label_create(ui_Status_Container_3);
lv_obj_set_width( ui_Status_Content_Cloud_Account_Id_Content_Label, lv_pct(100));
lv_obj_set_height( ui_Status_Content_Cloud_Account_Id_Content_Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Status_Content_Cloud_Account_Id_Content_Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Status_Content_Cloud_Account_Id_Content_Label,"12387612876312673dd");
lv_obj_set_style_text_color(ui_Status_Content_Cloud_Account_Id_Content_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Status_Content_Cloud_Account_Id_Content_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Status_Content_Cloud_Account_Id_Content_Label, &ui_font_Font_Book_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Status_Header_Back_Button, ui_event_Status_Header_Back_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Status_Screen, ui_event_Status_Screen, LV_EVENT_ALL, NULL);

}
